#
name: Deploy Frontend to AWS S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://temperature-monitor-client --delete

      - name: Invalidate CloudFront distribution
        run: aws cloudfront create-invalidation --distribution-id EFXRV4DU5IS1X --paths "/*"
